name: Wine Ubuntu CI

on:
  #schedule:
  #  - cron:  '25 9,21 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    #container:
    #  image: "ubuntu:25.04"
    env:
      DEBIAN_FRONTEND: noninteractive
      TZ: UTC
    steps:
      # - name: Install Git
      #   run: |
      #     apt-get update
      #     apt-get install -y git
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Compilation
        id: build
        shell: bash {0}
        run: |
          sudo dpkg --add-architecture i386 && sudo apt-get update
          sudo apt-get install -y aptitude
          sudo aptitude remove -y '?narrow(?installed,?version(deb.sury.org))'
          cd wine-tkg-git/wine-tkg-git

          patches=("silence-sc-unsupported-os")
          for file in "${patches[@]}"; do
              cp "../../patches/wine/$file.patch" "./wine-tkg-userpatches/${file%.patch}.mypatch"
          done

          sed -i 's/wayland_driver="false"/wayland_driver="true"/' customization.cfg

          sed -i 's/use_staging="true"/use_staging="false"/' customization.cfg
          #sed -i 's/use_ntsync="false"/use_ntsync="true"/' customization.cfg
          #sed -i 's/use_esync="true"/use_esync="false"/' customization.cfg
          #sed -i 's/use_fsync="true"/use_fsync="false"/' customization.cfg

          sed -i 's/staging_userargs="-W ntdll-NtAlertThreadByThreadId"/staging_userargs="-W ntdll-NtAlertThreadByThreadId -W ntdll-ForceBottomUpAlloc"/' ./wine-tkg-profiles/advanced-customization.cfg

          sed -i 's/_NOLIB32="false"/_NOLIB32="wow64"/' wine-tkg-profiles/advanced-customization.cfg
          echo '_ci_build="true"' >> customization.cfg
          touch tarplz
          yes|./non-makepkg-build.sh

          dir=$(find ./non-makepkg-builds -maxdepth 1 -type d -name 'wine-*' -printf '%f\n')
          lug_dirname="lug-$(echo "$dir" | cut -d. -f1-2)"
          mv "./non-makepkg-builds/$dir" "./non-makepkg-builds/$lug_dirname"
          echo "BUILD_DIR=$lug_dirname" >> $GITHUB_OUTPUT
      - name: Archive the artifacts
        uses: actions/upload-artifact@v4
        with:
          name:  ${{ steps.build.outputs.BUILD_DIR }}
          path: wine-tkg-git/non-makepkg-builds
